Skip missing source blend shapes and tell the user
System.ArgumentException: Blend shape index out of range with multiple blend shapes is only expected if a source blend shape is deleted at some point prior to this tool running. See #54